using Orchard.ContentManagement.Handlers;
using Orchard.Data;
using Orchard.ContentManagement;
using Orchard.Localization;
using Mod.ClientSettings.Models;

// This code was generated by Orchardizer
namespace Mod.ClientSettings.Handlers
{
	public class EditorGroupSettingsPartHandler : ContentHandler
    {
        public EditorGroupSettingsPartHandler() {
			Filters.Add(new ActivatingFilter<EditorGroupSettingsPart>("Site"));	
			T = NullLocalizer.Instance;
        }

		public Localizer T { get; set; }

		protected override void GetItemMetadata(GetContentItemMetadataContext context) {
            if (context.ContentItem.ContentType != "Site")
                return;
            base.GetItemMetadata(context);
            context.Metadata.EditorGroupInfo.Add(new GroupInfo(T("Client Settings")));
        }
    }
}