using System;
using Orchard.ContentManagement;
using Orchard.ContentManagement.Drivers;
using Mod.ClientSettings.Models;

// This code was generated by Orchardizer
namespace Mod.ClientSettings.Drivers
{
	public class EditorGroupSettingsPartDriver : ContentPartDriver<EditorGroupSettingsPart>
    {
        protected override string Prefix
        {
            get { return "EditorGroupSettingsPart"; }
        }


        protected override DriverResult Editor(EditorGroupSettingsPart part, dynamic shapeHelper)
        {
            return ContentShape("Parts_EditorGroupSettingsPart_Edit",
                () => shapeHelper.EditorTemplate(
                    TemplateName: "Parts/EditorGroupSettingsPart",
                    Model: part,
                    Prefix: Prefix))
					.OnGroup("Client Settings");
        }

        protected override DriverResult Editor(EditorGroupSettingsPart part, IUpdateModel updater, dynamic shapeHelper)
        {
            updater.TryUpdateModel(part, Prefix, null, null);
            return Editor(part, shapeHelper);
        }
    }
}