
using System;
using Orchard.ContentManagement;

// This code was generated by Orchardizer
namespace Mod.ClientSettings.Models
{
	public class EditorGroupSettingsPart : ContentPart
    {
     
        public string EditorGroups {
            get { return this.Retrieve(x => x.EditorGroups); }
            set { this.Store(x => x.EditorGroups, value); }
        }
    }
}